language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test app
  - coverage run --omit=*tests.py* manage.py test app
after_success:
  coveralls
